### ISSUE TITLE
Test Failures Prevent Installation?

### ISSUE THREAD

**Issue by VxJasonxV** [gingerhendrix/scrobbler2#1]
Hello!

I admit that I am new to the Ruby / Ruby Gem game, at least in so far as deviating from "gem install <gemname>", but I have two problems.

(1) I tried to simply run "gem install gingerhendrix-scrobbler2", but I am met with:
ERROR:  could not find gem gingerhendrix-scrobbler2 locally or in a repository

And yes, I have added gems.github.com as a source.

<pre>$ gem sources
*** CURRENT SOURCES ***

http://gems.rubyforge.org/
http://gems.github.com </pre>

(2) I attempted to download 0.0.3 and install it. The first thing that came to mind was simply to run "rake" inside the directory. Doing that seemed to work until a series of tests failed. (I'll provide that output if you wish)

I'm under the assumption that the test failures prevented anything meaningful from happening. Am I incorrect in this assumption? Would it be possible for me to simply run "rake install" or something similar and bypass any/all problems?

**Comment by gingerhendrix** [comment]
As for (1) - my bad, the gem was never properly published.  Try it again now, this should work.

As for (2) - if you want to install manually (or from the most recent source), download or checkout the code and run "rake install" to build and install the gem or "rake build" to build the gem.
Running "rake" by itself is equivalent to "rake test:unit", these tests should pass.  If they don't you're probably missing a dependency (scrobbler2 require httparty and active_support).  Please feel free to post the test output here if you need help.

**Comment by VxJasonxV** [comment]
I should have figured that and tried some other common commands in conjunction with rake.

However, yes indeed, I can now install directly via the gem command \o/. And with that, I've made the necessary changes and have hit the ground running. You're going to have two more issues in the next few minutes of suggestions that I've already come up with :).

Thanks again!

[edit]

Ok, I lied, only one new issue. The other was my own problem and it was just because I was an idiot :P.

Loving your updates so far! I'll need to branch out and start using more than just recent tracks.
