### ISSUE TITLE
Move api_key / api_secret into Initialization

### ISSUE THREAD

**Issue by VxJasonxV** [gingerhendrix/scrobbler2#2]
It is my opinion that api_key and api_secret shouldn't need to be defined as methods, and shouldn't need to be read in that way.

This is what I'm currently working with (keys scrambled, of course):
    user = Scrobbler2::User.new('VxJasonxV')
    user.api_key = '12345678901234567890123456789012'
    user.api_secret = '09876543210987654321098765432101'

I can't pin this on any one particular reason, but I would think these keys can, and should, be moved into the initialization. Something like so:
    user = Scrobbler2::User.new('VxJasonxV', '12345678901234567890123456789012', '09876543210987654321098765432101')

Is there any significant reason (guidelines, not "ruby-like", or other) that I don't know of that runs contrary to this idea?

**Comment by VxJasonxV** [comment]
In looking at this, I'm wondering if a higher level call for setting the api_key and api_secret are more practical. I note that the current implementation and my suggestion implementation, mean that you're quite possibly going to provide your api_key and api_secret as many times as you have unique objects in your script.

```
user = Scrobbler2::User()
user.api_key
user.api_secret

album = Scrobbler2::Album()
album.api_key
album.api_secret

artist = Scrobbler2::Artist()
artist.api_key
artist.api_secret

[...]
```

Is there a better idea here? Global variable? Constant? YAML File? Other Filesystem based config?

**Comment by gingerhendrix** [comment]
api_key and api_secret and session_key are all class attributes on Scrobbler2::Base you can simply set them once.
    Scrobbler2::Base.api_key = '12345678901234567890123456789012'
